name: Build & deploy to DEV slot

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "20.x"
  APP_NAME: "ase-proposal-files"  # App Service name
  SLOT_NAME: "dev"                # Slot name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node / frontend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: NODE_OPTIONS=--max_old_space_size=8192 npm run build

      - name: Copy built frontend into backend/static
        run: |
          rm -rf backend/static
          mkdir -p backend/static
          cp -r frontend/dist/* backend/static/

      # Optional: slim the zip
      - name: Remove frontend node_modules from package
        run: rm -rf frontend/node_modules

      - name: Create deployment zip (entire repo, preserves backend/ path)
        run: |
          zip -r app.zip . -x "**/.git/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Development
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to App Service (DEV slot)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          package: app.zip
